### ISSUE TITLE
Web Apps don't need no manual testing

### ISSUE THREAD

**Issue by HoverBaum** [hamburg-js/proposals#10]
## HamburgJS Talk Submission

**Talk Title:** Web Apps don't need no manual testing

**Talk Description:**

Manual testing has long been a well established part of software development. But often times it feels like a weight slowing us down. In this talk we will explore why manual testing is often blocking fast development cycles and how to improve the situation by having a computer do the clicking through the application. To this end we will explore Cypress as a fun and easy to get started tool.

Really a two part talk with:
1) Why you should do integration and end-to-end testing
2) How to use Cypress to do that

**Name**:

Hendrik Wallbaum

**Pronouns**:

he/him

**Twitter Handle (optional)**:

**Website (optional):**

https://hendrikwallbaum.de/

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We will keep this issue open throughout those months if you are not accepted the first time!

July
September
November

**Also:** 

The talk will have been presented at two different, company internal meet ups before July.

**Comment by dmbch** [comment]
@HoverBaum I think you already gave this talk at [React.HH](http://meetu.ps/e/H02dK/6pKF8/a), right?

Since there is significant overlap within our respective communities, we think it does not make much sense to feature it at HH.js as well.

Feel free to reopen if you disagree!

**Comment by HoverBaum** [comment]
Sounds fine to me.

I will open a new issue when I have a new talk 😁

Daniel Dembach <notifications@github.com> schrieb am Mi., 25. Sep. 2019,
19:43:
