### ISSUE TITLE
Streaming Tango Controls events to HTTP via Server-Sent Events

### ISSUE THREAD

**Issue by Ingvord** [hamburg-js/proposals#14]
## HH.js Lightning Talk Submission

**Talk Title:**

Streaming Tango Controls events to HTTP via Server-Sent Events

**Talk Description:**

Tango-Controls is an open source framework for building SCADA systems mainly used at big research facilities such as DESY, Hamburg. Tango Controls emits events related to hardware state changes, archive events etc. In this talk we cover the topic of how to export these events from Tango Controls protocol into HTTP via Server-Sent Events. Implementation details of server and client side will be given.

**Name**:

Igor Khokhriakov

**Pronouns**:

HZG, DESY Outstation, software solutions architect
Tango Controls Kernel developer

**Twitter Handle (optional)**:

**Website (optional):**

http://tango-controls.org
http://ingvord.ru

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We will keep this issue open throughout those months if you are not accepted the first time!

Jul, Aug, Nov 2019

**Comment by ZauberNerd** [comment]
@Ingvord thank you for your proposal, we have just accepted it for the 23rd of July.

Please read through the FAQ and keep in mind, that your talk should be limited to 5 Minutes:
https://github.com/hamburg-js/proposals/blob/master/speakers.md
