### ISSUE TITLE
[Proposal] Prisma 2: Modern database tools for Node.js and TypeScript

### ISSUE THREAD

**Issue by nikolasburk** [hamburg-js/proposals#15]
## HH.js Talk Submission

**Talk Title:**

Prisma 2: Modern database tools for Node.js and TypeScript

**Talk Description:**

Working with databases in Node.js/TypeScript can be painful. Traditional ORMs like Sequelize or TypeORM give you a head start but typically fall short once a project grows and becomes more complex. Performance issues and inefficient, generated queries are only few of the issues an ORM can introduce.

Prisma 2 provides three tools that simplify common database workflows for developers:

- Photon: A lightweight, auto-generated and type-safe database client (query builder)
- Lift: A declarative data modeling and migration tool
- Studio: Database GUI to simplify database workflows (e.g. data editing)

Prisma 2 takes a new approach to database workflows. The tools are based on the _Prisma schema_ which contains a data model definition. This data model is a declarative representation of your database schema. Photon is auto-generated based on this data model and provides a CRUD API to read and write data in your database. Lift can be used to perform migrations against the database by transitioning between various states of the data model.

In this talk, I will give a tour through the Prisma ecosystem and compare it to existing approaches for similar database workflows.

**Name**:

Nikolas Burk

**Pronouns**:

He/Him

**Twitter Handle (optional)**:

[@nikolasburk](https://www.twitter.com/nikolasburk)

**Months Available to Speak:** 

October, November

**Comment by ZauberNerd** [comment]
Hi @nikolasburk we have selected your talk for the next meetup (November 20th - https://www.meetup.com/hamburg-js/events/266383530/). Please check out the FAQ (https://github.com/hamburg-js/proposals/blob/master/speakers.md) and / or contact us if you have any questions. Cheers

**Comment by nikolasburk** [comment]
Hey there @ZauberNerd, sorry for the delay! Unfortunately I won't be able to speak at the Meetup next week since I'll be speaking at GOTO Copenhagen that day and won't be able to make it to Hamburg... 😐 my sincere apologies for not having updated my availability in time!! I'm withdrawing the proposal for now but will likely reopen the issue at some point when I'm sure I'm available.
