### ISSUE TITLE
Talk Proposal: From OOUX to Grapql to OOUX

### ISSUE THREAD

**Issue by lassediercks** [hamburg-js/proposals#17]
## HH.js Talk Submission

**Talk Title:**

From OOUX to Grapql to OOUX

**Talk Description:**

I'll give a brief introduction to OOUX using a fictional case. I'll talk about how it's quite handy to document your findings in graphlql and end with a ooux visualisation of a graphql schema written in vuejs.

**Name**:
Lasse Diercks

**Pronouns**:
he/him

**Twitter Handle (optional)**:
@lassediercks

**Website (optional):**
https://lassediercks.de 

**Months Available to Speak:** 
November,December, January

**Note:** Please checkout the [FAQs](https://github.com/hamburg-js/proposals/blob/master/speakers.md#how-long-is-my-talk) to plan for the duration of your talk

**Comment by herschel666** [comment]
Hi @lassediercks, we have selected your talk — on a short notice unfortunately — for the next meetup (November 20th - https://www.meetup.com/hamburg-js/events/266383530/). Are you able to do it? Then please check out the FAQ (https://github.com/hamburg-js/proposals/blob/master/speakers.md) and / or contact us if you have any questions. Cheers 😃

**Comment by lassediercks** [comment]
thanks for having me! https://twitter.com/escapedcat/status/1197220070872813568
