### ISSUE TITLE
“Must Work Without JavaScript”

### ISSUE THREAD

**Issue by j9t** [hamburg-js/proposals#19]
## HH.js Talk Submission

**Talk Title:** “Must Work Without JavaScript”

**Talk Description:** A brief inquiry into whether or (probably) not it’s still useful to make sure sites and apps work without JavaScript. Largely borrowing from https://meiert.com/en/blog/must-work-without-javascript/ but tailored to talk format, for HH.js.

**Name**: Jens Oliver Meiert

**Twitter Handle (optional)**: j9t

**Website (optional):** https://meiert.com/en/

**Months Available to Speak:** (no restrictions on my end at the moment other than knowing 2, preferably 3 weeks ahead of time; happy to work with your preferences)

**Comment by j9t** [comment]
Hi @dmbch—just saw the Meetup announcement that this talk was accepted and scheduled. Cheers!

Unfortunately, however, Nov 20 does not work for me for I have a recurring event these Wednesday nights (it’s safer to coordinate with me beforehand). Let’s look for an alternative over email (jens@meiert.com)!

**Comment by ZauberNerd** [comment]
Hi @j9t alright, we will select another talk for the 20th November and coordinate with you beforehand next time.

**Comment by herschel666** [comment]
Moin @j9t, we rather spontaneously scheduled an XMAS-edition on December, 11th. So it's pretty much on short-notice, but would you be able to give your talk at this metup?

**Comment by j9t** [comment]
Hi @herschel666 – this looks good, give me a sec to confirm. I’ll follow up here, most likely until tomorrow.

**Comment by j9t** [comment]
@herschel666, @dmbch, count me in! Please let me know if there’s anything special to keep in mind, otherwise I prepare something for a ~20 minutes talk and see you next Wednesday at SinnerSchrader!

**Comment by herschel666** [comment]
@j9t Awesome! See you next week.
