### ISSUE TITLE
Talk: UHU Projects is the new '64KB Demo'

### ISSUE THREAD

**Issue by sebs** [hamburg-js/proposals#26]
## HH.js Talk Submission

**Talk Title:** 

UHU Projects is the new '64KB Demo'

**Talk Description:**

Modern development with package managers has seen constant criticism from security professionals and software development advocates all together. A simple frontend project might contain thousands of dependencies just to get a web page shipped to the user. This creates a security issue through dependency to a lot of 3rd party code and a big gateway in terms of knowledge for new developers entering a project. To counter this, I have started to code against one arbitrary rule borrowed from old school demo parties where 64KB code must be enough to develop a demo; 100 dependencies is the maximum I allow for my development toolchain for js projects - build, test, deploy ship. This new minimalism let me choose my helpers very wisely and forces me to think twice about what open standards are out there on my machine, in the internet and the cloud and why NIH, Bike Shedding and YakShaving are not everything you have to think about developing software that is usable in the near future. We will have a look at my experiments: website, web component and backend to find out how modern JS and Typescript tools can help us to reduce the security impact of your toolchain, reduce stress and the amount of things 'you have to know'.

**Name**:

Sebastian Schürmann

**Pronouns**:

He/Him

**Twitter Handle (optional)**:

**Website (optional):**

**Months Available to Speak: Sept, Oct, Nov (Maybe August) 

**Note:** Please checkout the [FAQs](https://github.com/hamburg-js/proposals/blob/master/speakers.md#how-long-is-my-talk) to plan for the duration of your talk

**Comment by learosema** [comment]
Hi @sebs, our meetup group was pretty dead until now. We are finally reviving the meetup and there is going to be an in person meetup in [August 31 at Check24](https://www.meetup.com/de-DE/hamburg-js/events/294429119). Would you be willing to give your talk on that date?

Best regards,
Lea

**Comment by sebs** [comment]
oh Hello!
Yes and yes and yes!

**Comment by learosema** [comment]
Awesome 😍

**Comment by sebs** [comment]
added to my calendar

**Comment by learosema** [comment]
Thank you for this great talk, really enjoyed it 💯 are the slides available somewhere?

**Comment by sebs** [comment]
not yet. Ill wgive them a work over and publish them somewhere. I would be super happy for a shoutout then. Give me a bunch of days to get some help with it.

**Comment by learosema** [comment]
@sebs Thank you very much for your talk
