### ISSUE TITLE
Writing full-stack code without repeating yourself

### ISSUE THREAD

**Issue by noam-honig** [hamburg-js/proposals#27]
## HH.js Talk Submission

**Talk Title:**
Writing full-stack code without repeating yourself

**Talk Description:**
As full-stack developers, we write a lot of duplicate and boilerplate code for everyday things such as simple database CRUD, data validation, authorization, and data-type conversions. How can we use a modern web architecture but still maintain our code DRY and increase productivity?

In this live coding session, we'll turn a front-end React app into a full-stack app with code that is easy to write, follow, and, most importantly - maintain. Using: React, node js, express, Postgres and remult

**Name**:
Noam Honig

**Pronouns**:
He/Him

**Twitter Handle (optional)**:
@noamhonig

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We will keep this issue open throughout those months if you are not accepted the first time!
February / March / April

**Note:** Please checkout the [FAQs](https://github.com/hamburg-js/proposals/blob/master/speakers.md#how-long-is-my-talk) to plan for the duration of your talk
I can do it in 20 minutes, but I prefer 30-40 minutes including questions

Here's a link to a similar talk I gave at BudapestJS:
https://youtu.be/CnCaMQCu3Kc

**Comment by learosema** [comment]
Hi @noam-honig, our meetup group was pretty dead until now. We are finally reviving the meetup and there is going to be an in person meetup in [August 31 at Check24](https://www.meetup.com/de-DE/hamburg-js/events/294429119). Would you be willing to give your talk on that date?

Best regards,
Lea

**Comment by noam-honig** [comment]
Hi @learosema, sorry for the late response - I'll check my schedule and get back to you in the next few days.

Best

**Comment by learosema** [comment]
@noam-honig thank you. I'll reopen the issue so it's better findable in the list.

Best regards,
Lea

**Comment by noam-honig** [comment]
Hi @learosema 

I'm sorry, but I will not be able to make it.

Best

**Comment by learosema** [comment]
Hi @noam-honig, no worries, thank you very much for getting back and checking your calendar.
Best regards
Lea
