### ISSUE TITLE
Talk: We're PHP now – How Server Components will shape the future of JS

### ISSUE THREAD

**Issue by divslinger** [hamburg-js/proposals#29]
### Talk Title:
We're PHP now – How Server Components will shape the future of JS

### Talk Description:
Server Components are sparking a revolution in the JavaScript landscape, transforming the way we conceptualize and architect web applications. This talk breaks down the power and potential of this new trend while staying framework-agnostic. Delving into real-world examples, we'll discover how Server Components are redefining boundaries, enhancing user experiences, and setting new standards for app performance.

### Name:
Oskar Oldorf

### Pronouns:
He/Him

### Duration:
20 Minutes

### Website:
https://www.linkedin.com/in/oskaroldorf/

### Months Available to Speak:
August

**Comment by learosema** [comment]
Hi @divslinger, I'd like to accept your talk for the upcoming meetup in August 👍🏻

**Comment by learosema** [comment]
Hi @divslinger, just wanted to check in, would you confirm the talk for the meetup in August 31 at Check24?

**Comment by divslinger** [comment]
> Hi @divslinger, just wanted to check in, would you confirm the talk for the meetup in August 31 at Check24?

Yes @learosema, confirmed!

**Comment by learosema** [comment]
Thank you, accepted then 🥳

**Comment by learosema** [comment]
thank you very much ❤️
