### ISSUE TITLE
Introduction to JSON-LD

### ISSUE THREAD

**Issue by angelo-v** [hamburg-js/proposals#3]
## HamburgJS Talk Submission

**Talk Title:** Introduction to JSON-LD

**Talk Description:**

What is JSON-LD? How can it be used to decouple a JS frontend from an API? What are the differences to plain JSON and how can I start using it?

**Name**: Angelo Veltens

**Pronouns**:

**Twitter Handle (optional)**: [aveltens](https://twitter.com/aveltens)

**Website (optional):** https://angelo.veltens.org

**Months Available to Speak:** 

* May
* June (limited)
* July
* August

**Comment by ZauberNerd** [comment]
@angelo-v  thank you for your proposal, we have just accepted it for the 23rd of July.

Please read through the FAQ and keep in mind, that your talk should be limited to 20 Minutes:
https://github.com/hamburg-js/proposals/blob/master/speakers.md

**Comment by dmbch** [comment]
@angelo-v thanks again - and again, please read through the FAQ and keep in mind that your talk should be limited to 20 Minutes, although we could make it a bit longer this time since yours will be the only talk this time:
https://github.com/hamburg-js/proposals/blob/master/speakers.md
