### ISSUE TITLE
Lightning Talk: You might be a Product Engineer, you just don't know it yet

### ISSUE THREAD

**Issue by davguij** [hamburg-js/proposals#31]
## HH.js Lightning Talk Submission

**Talk Title:**
You might be a Product Engineer, you just don't know it yet

**Talk Description:**
I identify myself as a Product Engineer (which is coincidentally also my official job title!), and I believe that there are more out there. Are you one of us? If you don't know, I give you some hints to find out, and a couple of ideas of what to do next.

**Name**:
David Guijarro

**Pronouns (optional)**:
He/him

**Social Link (Twitter/Fediverse/LinkedIn/...) (optional)**:
https://www.linkedin.com/in/davidguijarro/

**Months Available to Speak:** 
31st August, September, October, November...

**Note:** 10-minute long if possible :)

**Comment by learosema** [comment]
Hi David, I would directly confirm your talk for August 31. 10 minutes is perfectly fine. Note to myself: I need to update the FAQ on talk durations. :)

**Comment by davguij** [comment]
Hey Lea. Thanks for confirming, I'll be there! 👍

**Comment by learosema** [comment]
@davguij thank you very much ❤️
