### ISSUE TITLE
Talk: Writing end to end tests using Playwright

### ISSUE THREAD

**Issue by reeversedev2** [hamburg-js/proposals#32]
## HH.js Talk Submission

**Talk Title:** 
Writing end to end tests using Playwright

**Talk Description:** 
Playwright is the emerging library to write e2e tests for your application. This talk will cover about the features like API mocking, routing, cookies, fixtures, steps for writing performant tests in Playwright. Talk will have hands-on code demo for writing the test.

**Name**: 
Prateek Gogia

**Pronouns (optional)**: 
He/him

**Social Link (Twitter/Fediverse/LinkedIn/...) (optional)**: 
https://www.linkedin.com/in/prateek-gogia/
https://twitter.com/reeversedev

**Website (optional):**

**Months Available to Speak:** 
August, September, October, November and December

**Note:** Please checkout the [FAQs](https://github.com/hamburg-js/proposals/blob/master/speakers.md#how-long-is-my-talk) to plan for the duration of your talk

**Comment by learosema** [comment]
Hi @reeversedev2 , sorry for the late reply, had a busy week, I'd like to accept your talk. Would you confirm for August 31? Sincerely, Lea

**Comment by reeversedev2** [comment]
Hey @learosema, I just finalized my travel plans last night. Can we make this part of future meetups after August?

**Comment by learosema** [comment]
@reeversedev2 sure, no problem. Right now there are no other neetups scheduled, will close it for now, will come back to you as soon as we got a next appointment.
