### ISSUE TITLE
[Talk] Prompt my Docs - ChatGPT for your own data

### ISSUE THREAD

**Issue by TimPietrusky** [hamburg-js/proposals#33]
## HH.js Talk Submission

**Talk Title:** 
[Prompt my Docs](https://github.com/failfa-st/prompt-my-docs) - ChatGPT for your own data

**Talk Description:**
Ever wished for a ChatGPT-like interaction tailored to your data? Join us as we explore the realm of [retrieval-augmented AI](https://arxiv.org/abs/2302.00083) through [hyv](https://github.com/failfa-st/hyv). We'll walk you through the steps — from preparing documents for the vector database [Weaviate](https://weaviate.io/), to crafting an AI agent that thinks like a JavaScript developer, leveraging [OpenAI's GPT-4](https://platform.openai.com/docs/api-reference) to extract insights directly from our curated data. Dive deep with us into the art of creating truly personalized AI experiences.

**Slides:**
I will tweak them for HH.js, but those are the ones from KarlsruheJS: 
https://failfa-st.github.io/prompt-my-docs-talk/karlsruhejs-20230809/

**Name**: 
Tim Pietrusky

**Pronouns (optional)**:
He/him

**Social Link (Twitter/Fediverse/LinkedIn/...) (optional)**:
https://www.linkedin.com/in/timpietrusky

**Website (optional):**
https://nerddis.co

**Months Available to Speak:** 
August, September, October, November, December

**Comment by TimPietrusky** [comment]
## Disclaimer 
* I created Prompt my Docs
* I worked on hyv
* Both projects are licensed under AGPL-v3
* I have no connection to Weaviate, I just love that they are open-source and anyone can run their database for free and I think that Weaviate is a nice database in the AI world
* The talk focuses on the concepts of In-Context RALM and tries to explain how someone could implement this with Typescript by using hyv, but the knowledge can also be used to implement this in other frameworks like langchain

**Comment by learosema** [comment]
Hi @TimPietrusky, I would like to accept your talk, would you confirm?

**Comment by TimPietrusky** [comment]
Hi @learosema, yes, I herby confirm! I'm super looking forward <3

**Comment by learosema** [comment]
@TimPietrusky thank you for speaking 💯 ❤️

**Comment by TimPietrusky** [comment]
@learosema thanks for providing me a stage and being such an awesome host!
