### ISSUE TITLE
Social Linked Data (Solid)

### ISSUE THREAD

**Issue by angelo-v** [hamburg-js/proposals#4]
## HamburgJS Talk Submission

**Talk Title:** Social Linked Data (Solid)

**Talk Description:**

The inventor of the Web, Tim Berners-Lee, introdruced a project called Solid, which is meant to re-decentralize the Social Web by extending the WWW as we know it with socially interlinked data. Solid shifts the way we have to think about building web applications fundamentally and gives interesting new opportunities. I will give an introduction of what exactly is Solid, how we can be part of it and how to build Solid applications.

**Name**: Angelo Veltens

**Pronouns**:

**Twitter Handle (optional)**: [aveltens](https://twitter.com/aveltens)

**Website (optional):** https://angelo.veltens.org

**Months Available to Speak:** 

* May
* June (limited)
* July
* August

**Comment by dmbch** [comment]
@angelo-v thank you for your proposal! We have just selected it for our May meetup next week.

**Comment by angelo-v** [comment]
Cool!
