### ISSUE TITLE
Web Components? Dead, aren't they?

### ISSUE THREAD

**Issue by DJCordhose** [hamburg-js/proposals#5]
## HamburgJS Talk Submission

**Talk Title:**

Web Components? Dead, aren't they?

**Talk Description:**

React has made the race and web components are now dead and useless. But really? Might there be reasons to actually use web components? This talk will investigate.

**Name**:

Oliver Zeigermann

**Pronouns**:

he/him

**Twitter Handle (optional)**:

DJCordhose

**Website (optional):**

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We will keep this issue open throughout those months if you are not accepted the first time!

July, September

**Comment by ZauberNerd** [comment]
@DJCordhose thank you for your proposal, we have just accepted it for the 23rd of July.

Please read through the FAQ and keep in mind, that your talk should be limited to 20 Minutes:
https://github.com/hamburg-js/proposals/blob/master/speakers.md
