### ISSUE TITLE
Unlocking New Capabilities for the Web 

### ISSUE THREAD

**Issue by tomayac** [hamburg-js/proposals#7]
## HamburgJS Talk Submission

**Talk Title:** Unlocking New Capabilities for the Web 

**Talk Description:** I offer to re-run Pete's and my talk from Google I/O (https://www.youtube.com/watch?v=GSiUzuB-PoI).

**Name**: Thomas Steiner

**Pronouns**: he/him

**Twitter Handle (optional)**: [@tomayac](https://twitter.com/tomayac)

**Website (optional):** https://blog.tomayac.com/

**Months Available to Speak:** May 23 would work.

**Comment by dmbch** [comment]
@tomayac thank you for your proposal! We have just selected it for our May meetup next week.

**Comment by tomayac** [comment]
Happy it’s of interest. I’ll need about 45min, hope that’s fine?
