### ISSUE TITLE
Talk Proposal: Monorepos and Node - 3 Scenarios

### ISSUE THREAD

**Issue by sebs** [hamburg-js/proposals#8]
## HamburgJS Talk Submission

**Talk Title:**

Monorepos and Node - 3 Scenarios

**Talk Description:**
With serverless, component based web architectures and other new 'hipster' tech, the use case for monorepos is strong - repositories encompassing whole projects are not so much the exception anymore and they keep the friction between teams and disciplines low. I want to presend 3 usecases for lerna.js monorepos: 

* a website project migrated to a mono repo 
* serverless web application on AWS
* General web component application 

**Name**:

Sebastian Schürmann 

**Pronouns**:

**Twitter Handle (optional)**:

**Website (optional):**

[Linkedin](https://www.linkedin.com/in/sebastian-sch%C3%BCrmann-7a642011/)

**Months Available to Speak:** 

May, June, July

**Comment by dmbch** [comment]
@sebs thank you for your proposal! We have just selected it for our May meetup next week.

**Comment by sebs** [comment]
oh great  t
