### ISSUE TITLE
E2E testing beyond the browser

### ISSUE THREAD

**Issue by s1hofmann** [hamburg-js/proposals#9]
## HamburgJS Talk Submission

**Talk Title:**
E2E testing beyond the browser

**Talk Description:**
E2E testing mostly happens on some kind of front end.
But front end does not stop at the browser.

We built an extensible open source framework with node to escape browser limitations in various ways.
If you are curious about what and how we did it, this talk is for you!

**Name**:
Simon Hofmann

**Pronouns**:
he / him

**Twitter Handle (optional)**:
s1hofmann

**Website (optional):**
https://simon-hofmann.org

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We will keep this issue open throughout those months if you are not accepted the first time!
Actually I'm only in Hamburg during Container Days 2019 (June 24. - 26.)
I know this is a bit on short notice, but the idea of talking at a meetup in Hamburg just struck me right now.

**Comment by ZauberNerd** [comment]
As June has passed already, I guess this can be closed now?
Feel free to re-open / create a new issue when the opportunity to speak in Hamburg arises again.
